apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: ntfy
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://{{ .Values.configMap.host }}
    attachment-cache-dir: "/var/cache/ntfy/attachments"
    attachment-total-size-limit: "1G"
    attachment-file-size-limit: "15M"
    attachment-expiry-duration: "1h"
    visitor-attachment-total-size-limit: "30M"
    visitor-attachment-daily-bandwidth-limit: "250M"
    web-root: /
