---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: tekton-ingress-stripprefix
  namespace: tekton-pipelines
spec:
  stripPrefix:
    prefixes:
      - /tekton
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-ingress
  namespace: tekton-pipelines
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.middlewares: tekton-pipelines-tekton-ingress-stripprefix@kubernetescrd
spec:
  rules:
    - host: {{ .Values.global.host }}
      http:
        paths:
          - path: /tekton
            pathType: Prefix
            backend:
              service:
                name: tekton-dashboard
                port:
                  number: 9097
