apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: tekton
spec:
  displayName: "build $(param.context)"
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  - name: tag
    type: string
  - name: context
    type: string
  workspaces:
  - name: shared-data
  - name: docker-credentials

  tasks:
  - name: fetch-source
    displayName: "clone $(params.context)"
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)

  - name: build-push
    runAfter: ["fetch-source"]
    displayName: "build $(params.context)"
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: CONTEXT
      value: $(params.context)
    - name: IMAGE
      value: $(params.image-reference):latest
    - name: EXTRA_ARGS
      value: ["--destination=$(params.image-reference):$(params.tag)"]
