---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-pipelines
  namespace: tekton-pipelines
spec:
  schedule: "0 5 * * 1,3,6"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: tekton-dashboard
          securityContext:
            fsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          initContainers:
          - name: clone-repo
            image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - |
              git clone {{ .Values.global.gitRepo }} /data/docker
              cat <<EOF > /data/docker/pvc.yaml
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Mi
              EOF
            volumeMounts:
            - name: data-dir
              mountPath: "/data"
          volumes:
          - name: data-dir
            emptyDir: {}

          containers:
          - name: run-all-pipelines
            image: gcr.io/tekton-releases/dogfooding/tkn:latest
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            imagePullPolicy: Always
            volumeMounts:
            - name: data-dir
              mountPath: /data
            command:
            - /bin/sh
            - -c
            - |
              for d in /data/docker/*/; do
                app=$(basename $d)
                tag=$(date -u +'%Y.%m.%d')
                tkn -n tekton pipeline start clone-build-push --prefix-name $app --param repo-url={{ .Values.global.gitRepo }} --param image-reference={{ .Values.global.dockerRegistry }}/$app --param tag=$tag --param context=$app --showlog -w name=shared-data,volumeClaimTemplateFile=/data/docker/pvc.yaml -w name=docker-credentials,secret=docker-credentials
                sleep 3
              done
