- name: "{{ item | basename }} - set facts"
  set_fact:
    name: "{{ item | basename }}"
    path: "{{ item }}"

- name: "{{ name }} - build helm values"
  set_fact:
    values: "{{ hostvars[inventory_hostname][name] | to_json }}"

- name: "{{ name }} - helm dependency update"
  ansible.builtin.raw: "helm dependency update {{ path }}"

- name: "{{ name }} - helm install"
  ansible.builtin.raw: "helm upgrade {{ name }} {{ path }} --install --set-json 'global={{ values }}' --wait"
