- name: register some facts
  set_fact:
    name: "{{ item | basename }}"
    path: "{{ item }}"
    values_file: "{{ item }}/values.yaml"

- name: "{{ name }} - building configmap"
  set_fact:
    str: "{{  hostvars[inventory_hostname][name] | to_json }}"

- name: "{{ name }} - helm dependency update"
  ansible.builtin.raw: "helm dependency update {{ path }}"

- name: "{{ name }} - helm install"
  ansible.builtin.raw: "helm upgrade {{ name }} {{ path }} --install --set-json 'global={{ values }}' --wait"
