---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        env:
        {{ if .Values.global.enableAdmin }}
        - name: ADMIN_TOKEN
          value: {{ .Values.global.adminToken }}
        {{ end }}
        - name: DOMAIN
          value: "https://{{ .Values.global.host }}"
        - name: TZ
          value: {{ .Values.timezone }}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: data-volume
          mountPath: /data/
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
