apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Name }}
data:
  access-key-id: {{ .Values.global.backup.conf.accessKeyId }}
  secret-access-key: {{ .Values.global.backup.conf.secretAccessKey }}
  zip-password: {{ .Values.global.backup.zipPassword }}
