apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-ipv4
  namespace: kube-system
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: traefik
    - ipBlock:
        cidr: ::0/0
