---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reg-ui-app
    name: reg-ui-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reg-ui-app
  template:
    metadata:
      labels:
        app: reg-ui-app
        name: reg-ui-app
      namespace: registry-ui
    spec:
      containers:
      - env:
        - name: CATALOG_ELEMENTS_LIMIT
          value: '1000'
        - name: CATALOG_MIN_BRANCHES
          value: '1'
        - name: CATALOG_MAX_BRANCHES
          value: '1'
        - name: DELETE_IMAGES
          value: 'true'
        - name: NGINX_PROXY_HEADER_Authorization
          value: {{ .Values.global.nginxHeaderAuth }}
        - name: NGINX_PROXY_PASS_URL
          value: {{ .Values.global.nginxProxyUrl }}
        - name: REGISTRY_SECURED
          value: 'false'
        - name: REGISTRY_TITLE
          value: Docker Registry UI
        - name: SHOW_CATALOG_NB_TAGS
          value: 'true'
        - name: SHOW_CONTENT_DIGEST
          value: 'true'
        - name: SINGLE_REGISTRY
          value: 'true'
        - name: TAGLIST_PAGE_SIZE
          value: '100'
        - name: TZ
          value: {{ .Values.timezone }}
        image: joxit/docker-registry-ui:latest
        imagePullPolicy: Always
        name: registry-ui
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
          name: registry-ui
          protocol: TCP
#      terminationGracePeriodSeconds: 0
