spec:
  pruner:
    disabled: false
    schedule: "0 2 * * *"    # at 02:00 AM
    resources:
    - taskrun
    - pipelinerun
    # NOTE: you can use either "keep" or "keep-since", NOT both
    keep:
    #keep-since: 4320.0 # 3 days (value is in minutes)
    keep-since: 2880.0  # 2 days
